name: deep_link
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  go_router: ^14.6.1
  app_links: ^6.3.2
  dio: ^5.7.0
  tie_fp: ^1.0.1
  tie_fp_dio: ^1.0.1
  pretty_dio_logger: ^1.4.0
  get_it: ^8.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
